### ISSUE TITLE
Unable to load the plugin to lemur

### ISSUE THREAD

**Issue by eenov8** [RcRonco/lemur_vault#23]
Hi,

After doing the Lemur configuration changes and doing a pip install on the plugin, when I try to do a lemur init, I am getting below error:

[2018-12-19 15:05:58,140] ERROR in factory: Failed to load plugin 'vault_issuer':
Traceback (most recent call last):
  File "/www/lemur/lemur/factory.py", line 186, in install_plugins
    plugin = ep.load()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/www/lemur/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/www/lemur/lib/python3.5/site-packages/lemur_vault/plugin.py", line 8, in <module>
    from lemur.plugins.lemur_vault import auth as vault_auth, VERSION as VAULT_PLUGIN_VER
ImportError: cannot import name 'auth'

Any advise.
AJ

**Comment by RcRonco** [comment]
Looks like lemur plugin is not installed in the lemur directory.
The directory should be ```/www/lemur/lemur/plugins/lemur_vault``` instead of ```/www/lemur/lib/python3.5/site-packages/lemur_vault```.
Thats the reason the plugin dont find ```lemur.plugins.lemur_vault``` to import ```auth```.

**Comment by eenov8** [comment]
So in my installation, I cloned the lemur_vault plugin inside /www/lemur/lemur/plugins directory and installed there...now there is a copy of the plugin both in this directory as well as the site-packages directly.
However, as per the lemur init logs, it's failing inside the site-packages directory.

I am using the latest versions of lemur and the vault plugin. Any suggestions on how to fix the same?

**Comment by RcRonco** [comment]
You need to remove the old installation from the site-packages.
Later check in python that you can ```import lemur```, and later ```import lemur.plugins.lemur_vault```

**Comment by RcRonco** [comment]
Closed due to inactivity
